### ISSUE TITLE
 make release bundles?

### ISSUE THREAD

**Issue by rfht** [Grumbel/sdl-jstest#12]
Hi,

I maintain a port of sdl-jstest on OpenBSD. It would be great if you would consider making releases of this awesome port on github, ideally with an upload of the sourcefiles/distfiles. The issue is that this is the only way that there is some guarantee that size/hash may not change when github changes some of its tools or other behind-the-scenes stuff. Our ports system (and that of other OS, too) checks the size and hash of the distfiles; so github's changes regularly break stuff unnecessarily.

Thanks!

**Comment by Grumbel** [comment]
Added a release for 0.2.2
