### ISSUE TITLE
Small typo causing wrong information when displaying a ball's values.

### ISSUE THREAD

**Issue by Astrophobia** [Grumbel/sdl-jstest#3]
In both sdl2-jstest.c, sdl-jstest.c, there is a small typo that causes the two values displayed for each 'ball' to be the same:
```
printw("  %2d: %6d %6d\n", i, balls[2*i+0], balls[2*i+0]);
```
Should be:
```
printw("  %2d: %6d %6d\n", i, balls[2*i+0], balls[2*i+1]);
```

**Comment by Grumbel** [comment]
What kind of hardware does actually emit ball events? Never seen any that does.
