### ISSUE TITLE
Instructions are out of date for compilation

### ISSUE THREAD

**Issue by siddharthist** [Grumbel/sdl-jstest#4]
Hey there, the AUR build of sdl2-jstest is broken, so I wanted to compile from source, but there is no Makefile, and `make` fails. I don't really know how to use CMake. Could you put updated instructions in the readme? Thank you!

**Comment by Grumbel** [comment]
Fixed in 378dc32

You can compile with:

mkdir build
cd build
cmake ..
make

**Comment by siddharthist** [comment]
Works perfectly. Thank you!
